name: Publish
on:
  workflow_run:
    workflows: ["CI"]
    types: [completed]
    branches:
      - main
concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  publish:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Authenticate with npm
        run: npm set "//registry.npmjs.org/:_authToken" ${{ secrets.NPM_TOKEN}}
      - name: Authenticate with github
        run: npm config set //npm.pkg.github.com/:_authToken=${{ secrets.GITHUB_TOKEN }}
      - name: Publish
        run: npm run publish
